server :
  port : ${SERVER_PORT:8080}

third:
  bootstrapServers: ${BOOTSTRAP_SERVERS:192.168.0.49:9092}
  callbackUrl: http://thirdservice:${server.port}/third/callback
  next:
    topic: fourth_topic

management:
  endpoints:
    web:
      exposure:
        include: "*"