server :
  port : ${SERVER_PORT:8080}

third:
  bootstrapServers: ${BOOTSTRAP_SERVERS:192.168.0.49:9092}
  callbackUrl: http://thirdservice:${server.port}/async/third/callback
  next:
    topic: fourth_topic
    syncUrl: http://fourthservice:8084/sync/fourth/process

management:
  endpoints:
    web:
      exposure:
        include: "*"