server :
  port : ${SERVER_PORT:8080}

second:
  next:
    asyncUrl: http://thirdservice:8083/async/third/process
    syncUrl: http://thirdservice:8083/sync/third/process

management:
  endpoints:
    web:
      exposure:
        include: "*"