server:
  port: ${TOMCAT_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"

grpc:
  server:
    port: ${GRPC_SERVER_PORT}

  client:
    fifth-service:
      address: static://${SERVER_HOST:localhost}:6085
      negotiation-type: plaintext