server :
  port : ${SERVER_PORT:8080}

fourth:
  next:
    url: http://fifthsync:7085/sync/fifth/process

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
