server :
  port : ${SERVER_PORT:8080}

first:
  next:
    asyncUrl: http://secondservice:8082/async/second/process
    syncUrl: http://secondservice:8082/sync/second/process

management:
  endpoints:
    web:
      exposure:
        include: "*"
