server :
  port : ${SERVER_PORT:8080}

fifth:
  bootstrapServers: ${SERVER_HOST}:9092
  topic: fifth_topic
  groupId: fifth_group
  next:
    url: http://${SERVER_HOST}:8086/sixth/process

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    kafka: OFF
