server :
  port : ${SERVER_PORT:8080}

fifth:
  bootstrapServers: ${SERVER_HOST}:9092
  topic: fifth_topic
  groupId: fifth_group
  next:
    asyncUrl: http://${SERVER_HOST}:8086/async/sixth/process
    syncUrl: http://${SERVER_HOST}:8086/sync/sixth/process

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    kafka: OFF
