server:
  port: ${TOMCAT_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"

grpc:
  server:
    port: ${SERVER_PORT}

  client:
    fourth-service:
      address: static://localhost:6084
      negotiation-type: plaintext