server :
  port : ${SERVER_PORT:8080}

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://${SERVER_HOST:localhost}:5432/reactive_database
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      username: mongodb
      password: mongodb
      uri: mongodb://mongodb:mongodb@${SERVER_HOST:localhost}:27017/reactive?authSource=admin
    redis:
      host: ${SERVER_HOST:localhost}
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
