server:
  port: ${TOMCAT_SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"

grpc:
  server:
    port: ${SERVER_PORT}

  client:
    sixth-service:
      address: static://localhost:6086
      negotiation-type: plaintext